title: Project

tabs:
  projectContent:
    extends: tabs/dashboard
    icon: dashboard
    
  projectFiles:
    extends: tabs/content
    icon: layers

  projectMetadata:
    extends: tabs/metadata
    icon: text

  projectEPub: 
    extends: tabs/settings/epub
    icon: settings