title: Project

columns:
  - width: 2/3
    sections:
      projectTableOfContentSection:
        type: fields
        fields:
          projectTableOfContent:
            type: pages
            label: 
              en: "Table of Contents"
              de: "Inhaltsverzeichnis"
            text: "{{ page.documentLevel.translate() }} {{ page.title }}"
            info: "{{ page.documentPart.translate().upper() }}"
            image: 
              query: page.image
            query: page.children
            subpages: true
            search: true
      projectPublishedDocumentSection:
        extends: sections/published
      projectDraftDocumentSection:
        extends: sections/drafts
      projectFilesSection:
        type: files
        headline:
          en: "Project Files"
          de: "Projektdateien"
        info: "{{ file.niceSize }}"
        layout: list
  - width: 1/3
    sections:
      projectDescriptionSection:
        type: fields
        fields: 
          projectDescription:
            type: textarea
            label: 
              en: "Description"
              de: "Beschreibung"
            help:
              en: "Short description of the project."
              de: "Kurze Beschreibung des Projekts."
      projectEpubSection:
        extends: sections/epub