title: Project

columns:
  - width: 2/3
    sections:
      projectPublishedDocuments:
        type: pages
        headline: 
          en: "Tabel of Content"
          de: "Inhalt"
        layout: list
        status: published
        text: "{{ page.title }}"
        info: "{{ page.documentPart.translate().upper() }}"
        create: 'Document'
      projectDraftDocuments:
        headline: 
          en: "Drafts"
          de: "Entwürfe"
        type: pages
        layout: list
        status: drafts
        text: "{{ page.title }}"
        info: "{{ page.documentPart.translate().upper() }}"
        create: 'Document'
  - width: 1/3
    sections:
      projectDescription:
        type: fields
        fields: 
          projectDescription:
            type: textarea
            label: 
              en: "Description"
              de: "Beschreibung"
            help:
              en: "Short description of the project."
              de: "Kurze Beschreibung des Projekts."
      projectCoverImage:
        type: files
        headline:
          en: "Cover Image"
          de: "Titelbild"
        text: "{{ file.filename }} ({{ file.dimensions }})"
        info: "ALT: {{ file.alt }}"
        layout: cards
        max: 1
        size: small
        image:
          ratio: 1/1
          cover: false
        template: cover
      projectFiles:
        type: files
        headline:
          en: "Project Files"
          de: "Projektdateien"
        info: "{{ file.dimensions }}"
        layout: list
        template: default