title: Project

tabs:
  projectContent:
    extends: tabs/projectContent
    icon: layers
    
  projectMetadata:
    extends: tabs/metadata
    icon: text

  projectFiles:
    extends: tabs/projectFiles
    icon: import

  projectEPub: 
    extends: tabs/epub
    icon: settings