title: Project

tabs:
  projectContent:
    extends: tabs/project/dashboard
    icon: dashboard
    
  projectFiles:
    extends: tabs/project/content
    icon: layers

  projectMetadata:
    extends: tabs/project/metadata
    icon: text

  projectEPub: 
    extends: tabs/project/settings/epub
    icon: settings