title: Site

columns:
  - width: 1/3
    sections:
      siteListedPages:
        headline: 
          en: "Project Overview"
          de: "Projektübersicht"
        type: pages
        status: listed
        min: 1
        layout: cards
        size: small
        image: 
          ratio: 3/2
          cover: false
          back: white
          query: site.image
        text: "{{ page.title }}"
  - width: 1/3
    sections:
      siteInfo:
        type: fields
        fields: 
          siteInfo:
            type: info
            label: 
              en: "Info"
              de: "Info"
            text:
              en: "Simple web-based editorial system built on top of Kirby with pageJS and saxonJS modules."
              de: "Einfacher web-basiertes Editorialstytem aufbauend auf Kirbe mit pageJS und saxonJS Modulen."
          siteOptions:
            type: headline
            label: 
              en: Options
              de: Optionen
            numbered: false
          siteDocumentParts:
            label: 
              en: Document Parts
              de: Dokumenteile
            type: tags
            options:
              - "titlepages"
              - "frontmatter"
              - "bodymatter"
              - "backmatter"
            help:
              en: e.g. for parsX export
              de: z.B. für parsX-Export
          siteDocumentTypes:
            label: 
              en: Document Types
              de: Dokumenarten
            type: tags
            options:
              # Frontmatter
              - "cover"
              - "titlepage"
              - "halftitlepage"
              - "maintitle"
              - "copyright-page"
              - "imprint"
              - "imprimatur"
              - "contributors"
              - "colophon"
              - "other-credits"
              - "errata"
              - "revision-history"
              - "dedication"
              - "epigraph"
              - "toc"
              - "foreword"
              - "preface"
              - "acknowledgments"
              - "introduction"
              - "prologe"
              - "preamble"
              # Bodymatter
              - "part"
              - "division"
              - "chapter"
              - "chapter-subchapter"
              - "volume"
              # Backmatter
              - "epilogue"
              - "afterword"
              - "conclusion"
              - "appendix"
              - "glossary"
              - "loi"
              - "lot"
              - "bibliography"
              - "index"
              - "credits"              
            help:
              en: e.g. for landmarks and epub:type attribute in ePubs
              de: z.B. für Landmarks und epub:type-Attribut in ePubs
          siteDocumentRoles:
            label: 
              en: Document Roles
              de: Dokumenrollen
            type: tags
            options:
              # Frontmatter
              - "cover"
              - "titlepage"
              - "halftitlepage"
              - "maintitle"
              - "copyright-page"
              - "imprint"
              - "imprimatur"
              - "contributors"
              - "colophon"
              - "other-credits"
              - "errata"
              - "revision-history"
              - "dedication"
              - "epigraph"
              - "toc"
              - "foreword"
              - "preface"
              - "acknowledgments"
              - "introduction"
              - "prologe"
              - "preamble"
              # Bodymatter
              - "part"
              - "division"
              - "chapter"
              - "chapter-subchapter"
              - "volume"
              # Backmatter
              - "epilogue"
              - "afterword"
              - "conclusion"
              - "appendix"
              - "glossary"
              - "loi"
              - "lot"
              - "bibliography"
              - "index"
              - "credits"              
            help:
              en: e.g. for role attribute in ePubs
              de: z.B. für role-Atribite in ePubs
  - width: 1/3
    sections:
      siteUnlistedPages:
        headline: 
          en: "Pages"
          de: "Seiten"
        type: pages
        layout: list
        status: unlisted
        text: "{{ page.title }}"
      siteDraftPages:
        headline: 
          en: "Drafts"
          de: "Entwürfe"
        type: pages
        layout: list
        status: drafts
        text: "{{ page.title }}"
        create: 'Projects'
      siteFiles:
        type: files
        headline:
          en: "Files"
          de: "Dateien"
        layout: list