title: Site

columns:
  - width: 1/3
    sections:
      siteListedPages:
        headline: 
          en: "Library"
          de: "Bibliothek"
        type: pages
        status: listed
        min: 1
        layout: cards
        size: small
        image: 
          ratio: 3/2
          cover: false
          back: white
          query: site.image
        text: "{{ page.title }}"
  - width: 1/3
    sections:
      siteInfo:
        type: fields
        fields: 
          siteInfo:
            type: info
            label: 
              en: "Info"
              de: "Info"
            text:
              en: "Simple web-based editorial system built on top of Kirby with pageJS and saxonJS modules."
              de: "Einfacher web-basiertes Editorialstytem aufbauend auf Kirbe mit pageJS und saxonJS Modulen."
          siteOptions:
            type: headline
            label: 
              en: Options
              de: Optionen
            numbered: false
          siteDocumentParts:
            label: 
              en: Document Parts
              de: Dokumenteile
            type: tags
            options:
              - "titlepages"
              - "frontmatter"
              - "bodymatter"
              - "backmatter"
            help:
              en: e.g. for parsX export
              de: z.B. für parsX-Export
          siteDocumentLandmarks:
            label: 
              en: Landmarks
              de: Landmarks
            type: tags
            options:
              # Dokumentaufbau
	            - "cover"
	            - "frontmatter"
              - "bodymatter"
              - "backmatter"
              # Dokumentelemente
              - "epigraph"
              - "conclusion"
              - "afterword"
              - "warning"
              - "epilogue"
              - "foreword"
              - "introduction"
              - "prologue"
              - "preface"
              - "preamble"
              - "notice"
              # Referenzen
              - "landmarks"
              - "lot"
              - "index"
              - "colophon"
              - "appendix"
              - "loi"
              - "toc"
              # Glossare
              - "glossary"
              - "glossterm"
              - "glossdef"
              # Bibliographien
              - "biblioentry"
              - "bibliography"
              # Titelei
              - "imprint"
              - "errata"
              - "copyright-page"
              - "acknowledgments"
              - "other-credits"
              - "titlepage"
              - "imprimatur"
              - "contributors"
              - "halftitlepage"
              - "dedication"
              # Anmerkungen
              - "footnotes"
              - "rearnotes"
              # Titelelemente
              - "bridgehead"
              - "title"
              - "halftitle"
              - "fulltitle"
              - "subtitle"
              - "covertitle"     
            help:
              en: "e.g. for landmarks in ePubs"
              de: "z.B. für Landmarks ePubs"
          siteDocumentTypes:
            label: 
              en: Document Types
              de: Dokumenarten
            type: tags
            options:
              # Dokumentaufbau
	            - "cover"
	            - "frontmatter"
              - "bodymatter"
              - "backmatter"
              # Unterteilungen
              - "volume"
              - "part"
              - "chapter"
              - "subchapter"
              - "division"
              # Dokumentelemente
              - "epigraph"
              - "conclusion"
              - "afterword"
              - "warning"
              - "epilogue"
              - "foreword"
              - "introduction"
              - "prologue"
              - "preface"
              - "preamble"
              - "notice"
              # Referenzen
              - "landmarks"
              - "lot"
              - "index"
              - "colophon"
              - "appendix"
              - "loi"
              - "toc"
              # Glossare
              - "glossary"
              - "glossterm"
              - "glossdef"
              # Bibliographien
              - "biblioentry"
              - "bibliography"
              # Titelei
              - "imprint"
              - "errata"
              - "copyright-page"
              - "acknowledgments"
              - "other-credits"
              - "titlepage"
              - "imprimatur"
              - "contributors"
              - "halftitlepage"
              - "dedication"
              # Ergänzungen
              - "help"
              - "sidebar"
              - "annotation"
              - "marginalia"
              - "practice"
              # Anmerkungen
              - "note"
              - "footnote"
              - "rearnote"
              - "footnotes"
              - "rearnotes"
              # Titelelemente
              - "bridgehead"
              - "title"
              - "halftitle"
              - "fulltitle"
              - "subtitle"
              - "covertitle"
              # Textauszeichnungen
              - "concluding-sentence"
              - "keyword"
              - "topic-sentence"
              # Verweise
              - "annoref"
              - "noteref"
              # Paginierung
              - "page-list"
              - "pagebreak"     
            help:
              en: "e.g. for epub:type attribute in ePubs"
              de: "z.B. für epub:type-Attribut in ePubs"
          siteDocumentRoles:
            label: 
              en: "Document Roles"
              de: "Dokumenrollen"
            type: tags
            options:
              # Frontmatter
              - "cover"
              - "titlepage"
              - "halftitlepage"
              - "maintitle"
              - "copyright-page"
              - "imprint"
              - "imprimatur"
              - "contributors"
              - "colophon"
              - "other-credits"
              - "errata"
              - "revision-history"
              - "dedication"
              - "epigraph"
              - "toc"
              - "foreword"
              - "preface"
              - "acknowledgments"
              - "introduction"
              - "prologe"
              - "preamble"
              # Bodymatter
              - "part"
              - "division"
              - "chapter"
              - "chapter-subchapter"
              - "volume"
              # Backmatter
              - "epilogue"
              - "afterword"
              - "conclusion"
              - "appendix"
              - "glossary"
              - "loi"
              - "lot"
              - "bibliography"
              - "index"
              - "credits"              
            help:
              en: e.g. for role attribute in ePubs
              de: z.B. für role-Atribite in ePubs
  - width: 1/3
    sections:
      siteUnlistedPages:
        headline: 
          en: "Pages"
          de: "Seiten"
        type: pages
        layout: list
        status: unlisted
        text: "{{ page.title }}"
      siteDraftPages:
        headline: 
          en: "Drafts"
          de: "Entwürfe"
        type: pages
        layout: list
        status: drafts
        text: "{{ page.title }}"
        create: 'Projects'
      siteFiles:
        type: files
        headline:
          en: "Files"
          de: "Dateien"
        layout: list